// Mock data for services
export const mockServices = [
  {
    id: '1',
    name: 'Oil Change',
    description: 'Professional oil change service',
    price: 49.99,
    category: 'Maintenance',
    rating: 4.8,
    available: true,
    duration: '30 mins',
  },
  {
    id: '2',
    name: 'Tire Replacement',
    description: 'Premium tire replacement and balancing',
    price: 179.99,
    category: 'Tires',
    rating: 4.6,
    available: true,
    duration: '1 hour',
  },
  {
    id: '3',
    name: 'Battery Replacement',
    description: 'Battery installation and check',
    price: 129.99,
    category: 'Electrical',
    rating: 4.7,
    available: true,
    duration: '45 mins',
  },
  {
    id: '4',
    name: 'Brake Service',
    description: 'Brake inspection and maintenance',
    price: 199.99,
    category: 'Brakes',
    rating: 4.9,
    available: false,
    duration: '1.5 hours',
  },
  {
    id: '5',
    name: 'AC Service',
    description: 'Air conditioning system service',
    price: 89.99,
    category: 'Climate',
    rating: 4.5,
    available: true,
    duration: '1 hour',
  },
  {
    id: '6',
    name: 'Car Wash',
    description: 'Premium exterior and interior wash',
    price: 39.99,
    category: 'Cleaning',
    rating: 4.7,
    available: true,
    duration: '45 mins',
  },
];

// Mock data for providers
export const mockProviders = [
  {
    id: '1',
    name: 'AutoCare Solutions',
    email: 'info@autocare.com',
    phone: '555-0101',
    location: 'Downtown',
    rating: 4.8,
    services: ['1', '2', '3', '5', '6'],
  },
  {
    id: '2',
    name: 'Quick Car Service',
    email: 'contact@quickcar.com',
    phone: '555-0102',
    location: 'Midtown',
    rating: 4.6,
    services: ['1', '4', '5'],
  },
  {
    id: '3',
    name: 'Elite Auto Repair',
    email: 'service@eliteauto.com',
    phone: '555-0103',
    location: 'Uptown',
    rating: 4.9,
    services: ['2', '3', '4', '6'],
  },
];
